deployment:
  imageURL: #AWS ECR catalogue repository URL where image is pushed to through jenkins piepline
  imageversion: IMAGE_VERSION
hpa:
  maxReplicas: 10
  Utilisation: 75
configMap:
  MONGO_URL: mongodb://mongodb:27017/catalogue